### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Giacomo213342** [amistaa/discord-youtube-notification#1]
/root/yt/node_modules/rss-converter/dist/src/index.js:188
                            obj.feed.items.link = obj.feed.items.link._attrs.href;
                                                                 ^

TypeError: Cannot read property 'link' of undefined
    at Object.<anonymous> (/root/yt/node_modules/rss-converter/dist/src/index.js:188:66)
    at step (/root/yt/node_modules/rss-converter/dist/src/index.js:43:23)
    at Object.next (/root/yt/node_modules/rss-converter/dist/src/index.js:24:53)
    at fulfilled (/root/yt/node_modules/rss-converter/dist/src/index.js:15:58)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
root@vmi551015:~/yt# node index.js
Amista is cool uwu.
/root/yt/node_modules/rss-converter/dist/src/index.js:188
                            obj.feed.items.link = obj.feed.items.link._attrs.href;
                                                                 ^

TypeError: Cannot read property 'link' of undefined
    at Object.<anonymous> (/root/yt/node_modules/rss-converter/dist/src/index.js:188:66)
    at step (/root/yt/node_modules/rss-converter/dist/src/index.js:43:23)
    at Object.next (/root/yt/node_modules/rss-converter/dist/src/index.js:24:53)
    at fulfilled (/root/yt/node_modules/rss-converter/dist/src/index.js:15:58)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

PLZ SAVE ME I need this bot lol

**Comment by ExXxO** [comment]
Is the file links.json-File available ?

**Comment by Dextroamphetamine** [comment]
change link to links

**Comment by fitzydev** [comment]
Switch to rss-parser -- then try adjusting code to rss.parseURL

**Comment by modinodr** [comment]
Hi, I have the same problem and I can't adjust, please help.

**Comment by Giacomo213342** [comment]
where should I edit this?
